name: Go

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24"]
    name: Lint Go ${{ matrix.go-version == '1.24' && '(latest)' || '(old)' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libolm-dev libolm3 libgtk-3-dev libwebkit2gtk-4.1-dev libsoup-3.0-dev
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"
          mkdir -p web/dist
          touch web/dist/empty

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: pre-commit/action@v3.0.1

      - name: Test
        run: go test -v ./...
